#!/usr/bin/env python3

import ansible.config.manager
import ansible.parsing.dataloader
import ansible.inventory.manager

configuration = ansible.config.manager.ConfigManager()
dataloader = ansible.parsing.dataloader.DataLoader()

sources = configuration.data.get_setting("DEFAULT_HOST_LIST").value
inventory = ansible.inventory.manager.InventoryManager(loader=dataloader, sources=sources)

groups = inventory.get_groups_dict()

hosts = {}
for group in groups:
    if group == "all":
       continue
    for hostname in groups[group]:
        if hostname in hosts:
            if not group in hosts[hostname]:
                hosts[hostname].append(group)
        else:
            hosts[hostname] = [group]

for hostname in sorted(hosts.keys()):
    groups = sorted(hosts[hostname])
    print("%s %s" % (hostname, " ".join(groups)))
